#!/bin/sh

set -e

. /usr/share/debconf/confmodule

# using this greeter?
GREETER=
DEB_HOST_MULTIARCH=$(dpkg-architecture -qDEB_HOST_MULTIARCH)
if db_get shared/lightdm-greeter; then
  GREETER="$RET"
fi

if [ -n "${GREETER}" ];
then
  LIGHTDM_SET_DEFAULTS=/usr/lib/${DEB_HOST_MULTIARCH}/lightdm/lightdm-set-defaults
  if [ -x "${LIGHTDM_SET_DEFAULTS}" ];
  then
    "${LIGHTDM_SET_DEFAULTS}" --greeter "${GREETER}"
  fi
fi
db_stop || true

#DEBHELPER#

exit 0
